language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d

before_script:
  - cd ../../

script:
  - mvn clean
  - mvn test
