language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d

before_script:
  - cd ../../

script:
  - mvn clean
  - mvn package
  - mvn test
  - mvn test -Ptest-consumer
  - mvn test -Ptest-business